### PR TITLE
Property accessor is not available for certain ognl expressions.

### PR DESCRIPTION
**Pull request by anydoby**
In my case I wanted to validate a collection of objects without validating the nested objects, like this:

    @IsInvariant
    @AssertNull(target = "jxpath:.[deferred]")
    public List<Instrument> getSubentities()
    {
        .....
    }

This essentially checks that the subentities collection has no "deferred" instruments (that's from my domain of course). Previously this would throw an unclear exception because the result.targetAccessor is null.

### CODE REVIEW

**Comment by sebthom** [comment]
Would you mind adding a test case for your scenario? I can't reproduce this, but maybe I just misunderstand the issue. Thanks.

**Comment by anydoby** [comment]
Sure. Will make one, but in the morning :-)
24 июня 2016 г. 11:36 PM пользователь "Sebastian Thomschke" <
notifications@github.com> написал:

**Comment by anydoby** [comment]
Good morning Sebastian,

Sorry for the early e-mail, I am not really familiar with GitHub pull
request system. Looks like my unit test was added to it after my commit. It
illustrates what I was trying to achieve - namely validating a class
invariant by using AssertNull with a jxpath expression which select
potentially wrong children of an object. Had to debug jxpath itself to
understand why a simple expression like this "jxpath:.[not(happy)]" always
evaluates to false until I actually downloaded jxpath sources and saw the
unit tests for boolean. They have weird syntax for matching "not" true
nodes, but this does achieve what I want in one line. Without the fix I
would have to write a separate class (which I already do, since we cannot
use custom builds of open-source libraries in our products so far).

If the fix is ok and the test does not contradict the philosophy of Oval
what would be a date when you can release another version of the library? I
can of course use snapshot for a while :) but release looks better.

2016-06-25 0:11 GMT+02:00 Sergey Zolotaryov <anydoby@gmail.com>:

> Sure. Will make one, but in the morning :-)
> 24 июня 2016 г. 11:36 PM пользователь "Sebastian Thomschke" <
> notifications@github.com> написал:
>
>> Would you mind adding a test case for your scenario? I can't reproduce
>> this, but maybe I just misunderstand the issue. Thanks.
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/sebthom/oval/pull/1#issuecomment-228468014>, or mute
>> the thread
>> <https://github.com/notifications/unsubscribe/AJhNh3Ru4jVISk8M6DNnAx09V8qbVFBdks5qPE3kgaJpZM4I9r8j>
>> .
>>
>


-- 
Best regards,
Sergey Zolotaryov

**Comment by sebthom** [comment]
I had a look at your test case. The problem is, that the target expression doesn't point to a single object in the object graph. However, the idea of the target expression is to point to a new single "root" object that will be used for application of the validation constraint.

I changed the JXPath navigator implementation that in case multiple matches are found a proper navigation result is returned pointing to the first match.

So with the latest change you would want to change expression from
```
    @AssertNull(target="jxpath:.[happy = false()]") 
    List<Person> people = new ArrayList<NoTargetAccessorTest.Person>();
```
to
```
    @AssertTrue(target="jxpath:.[@happy = 0]/happy") 
    List<Person> people = new ArrayList<NoTargetAccessorTest.Person>();
```
The target expression will then point to the "happy" property of the first unhappy person in the list. Then the validator will check the AssertTrue constraint against that property - which results in the desired  constraint violation.

**Comment by anydoby** [comment]
This example is also fine. I guess it needs a decent example in the
userguide then since it's a bit counter intuitive to return one element
when filtering over a collection (no offence of course). Is this feature
available in current snapshot?

I also got a wrong expression at the beginning that I could just validate
elements of a collection with just one assert annotation in the owner
class. That's why I started this jxpath exploration :)

I had a look at your test case. The problem is, that the target expression
doesn't point to a single object in the object graph. However, the idea of
the target expression is to point to a new single "root" object that will
be used for application of the validation constraint.

I changed the JXPath navigator implementation that in case multiple matches
are found a proper navigation result is returned pointing to the first
match.

So with the latest change you would want to change expression from

    @AssertNull(target="jxpath:.[happy = false()]")
    List<Person> people = new ArrayList<NoTargetAccessorTest.Person>();

to

    @AssertTrue(target="jxpath:.[@happy = 0]/happy")
    List<Person> people = new ArrayList<NoTargetAccessorTest.Person>();

The target expression will then point to the "happy" property of the first
unhappy person in the list. Then the validator will check the AssertTrue
constraint against that property - which results in the desired constraint
violation.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/sebthom/oval/pull/1#issuecomment-228558596>, or mute
the thread
<https://github.com/notifications/unsubscribe/AJhNh-xnQedZWGODlDsPXudDdOiAXVSjks5qPWBPgaJpZM4I9r8j>
.

**Comment by sebthom** [comment]
The changes are in the latest snapshot at http://oval.sourceforge.net/mvn-repo/snapshot/net/sf/oval/oval/1.86-SNAPSHOT/

**Comment by anydoby** [comment]
Cool, I'd like to offer some other enhancements this week.
26 июня 2016 г. 1:39 PM пользователь "Sebastian Thomschke" <
notifications@github.com> написал:

**Comment by anydoby** [comment]
Hi Sebastian.

I tried adding other features to the oval but it looks like it's very
difficult to work with the source:

1) It does not build with maven. Complains about missing toolchain [sun
1.5] I tried declaring one with my existing jdk (1.8) but some unit tests
fail and I'm afraid of breaking more.

2) If I import the project in Eclipse unit tests that use TestGuardAspect
fail to compile because AspectJ does not build the *.aj files (is there a
reason to still stick to this format of aspects?). If I rename the
*.java.off to *.java then the tests do compile but when I launch them
Eclipse hangs.

How do you work with the project? Are you using any IDE?

-- 
Best regards,
Sergey Zolotaryov

**Comment by sebthom** [comment]
Hi Sergey,

1) the OVal build uses the maven toolchain plugin which allows you to run maven and it's plugins with a different JDK (e.g. Java8) than which is used for compilation and testing (Java5 in this case). See http://maven.apache.org/ref/3.3.9/maven-core/toolchains.html
My config looks like this:
```xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<toolchains>
<toolchain><type>jdk</type><provides><version>1.5</version><vendor>sun</vendor></provides><configuration><jdkHome>C:\apps\dev\java\sun_jdk1.5.0_22</jdkHome></configuration></toolchain>
<toolchain><type>jdk</type><provides><version>1.8</version><vendor>sun</vendor></provides><configuration><jdkHome>C:\apps\dev\java\sun_jdk1.8.0_91</jdkHome></configuration></toolchain>
</toolchains>
```

2) In Eclipse you need to install the AspectJ Development Tools http://www.eclipse.org/ajdt/
    I didn't get the pure Java Aspect classes working correctly so I sticked with the .aj files which do their job.

Cheers,
Seb

**Comment by anydoby** [comment]
Hi Sebastian,

Thanks for the instructions (I have worked with ajdt and maven for years,
by the way), but they don't seem to work. Maven compiles the aj files, but
not eclipse. Looks like you either have a certain combination of
eclipse/ajdt installed, or an older maven that works for you. I'll try to
figure out :-) do you run builds locally or on some build server where I
can lookup the environment?
29 июня 2016 г. 11:59 PM пользователь "Sebastian Thomschke" <
notifications@github.com> написал:

**Comment by anydoby** [comment]
Ok. With the JDK5 in a toolchain it does not build at all:

[INFO] --- maven-surefire-plugin:2.19.1:test (default-test) @ oval ---
[INFO] Toolchain in maven-surefire-plugin:
JDK[/home/sergey/java/jdk1.5.0_22]

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Error occurred during initialization of VM
java/lang/NoClassDefFoundError: java/lang/Object

Results :

Tests run: 0, Failures: 0, Errors: 0, Skipped: 0

[INFO]
------------------------------------------------------------------------
[INFO] BUILD FAILURE


If I put JDK8 to the toolchains.xml it builds but the unit tests fail:

Results :

Tests in error:
  XMLConfigurationTest.testImportedFile:133 » Conversion -1 : -1
---- Debugging ...
  XMLConfigurationTest.testSerializedObjectConfiguration:263 »
ArrayIndexOutOfBounds
  ValidatorSpringBeanTest.testValidatorSpringBean:23 » BeanCreation Error
creati...
  CustomXMLConstraintTest.testCustomXMLConstraint:17 » Conversion -1 : -1
---- D...
  XMLConfigurationTest.testImportedFile:70 » Conversion -1 : -1
---- Debugging i...
  XMLConfigurationTest.testSerializedObjectConfiguration:188 »
ArrayIndexOutOfBounds

Tests run: 171, Failures: 0, Errors: 6, Skipped: 0

[INFO]
------------------------------------------------------------------------
[INFO] BUILD FAILURE

I don't think this whole toolchain idea is credible to keep it in the
build, it's just not repeatable from setup to setup. Moreover it confuses
Eclipse to the point where it does not recognize scr folders at all :(



2016-06-30 8:19 GMT+02:00 Sergey Zolotaryov <anydoby@gmail.com>:

> Hi Sebastian,
>
> Thanks for the instructions (I have worked with ajdt and maven for years,
> by the way), but they don't seem to work. Maven compiles the aj files, but
> not eclipse. Looks like you either have a certain combination of
> eclipse/ajdt installed, or an older maven that works for you. I'll try to
> figure out :-) do you run builds locally or on some build server where I
> can lookup the environment?
> 29 июня 2016 г. 11:59 PM пользователь "Sebastian Thomschke" <
> notifications@github.com> написал:
>
> Hi Sergey,
>>
>> 1) the OVal build uses the maven toolchain plugin which allows you to run
>> maven and it's plugins with a different JDK (e.g. Java8) than which is used
>> for compilation and testing (Java5 in this case). See
>> http://maven.apache.org/ref/3.3.9/maven-core/toolchains.html
>> My config looks like this:
>>
>> <?xml version="1.0" encoding="ISO-8859-1"?>
>> <toolchains>
>> <toolchain><type>jdk</type><provides><version>1.5</version><vendor>sun</vendor></provides><configuration><jdkHome>C:\apps\dev\java\sun_jdk1.5.0_22</jdkHome></configuration></toolchain>
>> <toolchain><type>jdk</type><provides><version>1.8</version><vendor>sun</vendor></provides><configuration><jdkHome>C:\apps\dev\java\sun_jdk1.8.0_91</jdkHome></configuration></toolchain>
>> </toolchains>
>>
>> 2) In Eclipse you need to install the AspectJ Development Tools
>> http://www.eclipse.org/ajdt/
>> I didn't get the pure Java Aspect classes working correctly so I sticked
>> with the .aj files which do their job.
>>
>> Cheers,
>> Seb
>>
>> —
>> You are receiving this because you modified the open/close state.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/sebthom/oval/pull/1#issuecomment-229502134>, or mute
>> the thread
>> <https://github.com/notifications/unsubscribe/AJhNhydit1CkclkYpt94CXnhyLVjmUDNks5qQurBgaJpZM4I9r8j>
>> .
>>
>


-- 
Best regards,
Sergey Zolotaryov

**Comment by sebthom** [comment]
I am building it on an Ubuntu server via Jenkins, locally in Win10 64bit in the command line (currently Maven 3.3.9), as well as in a 32bit Eclipse installation (currently Mars SR2). I am not using any magic settings that I am aware of.

You need to ensure that Maven itself is launched with a JDK it supports. I think Java7 is it's current minimum. When the toolchains.xml is configured properly Maven will fork processes for compilation and testing using the JDK defined in the toolchains.xml as jdk 1.5.

"java/lang/NoClassDefFoundError: java/lang/Object" sounds like an incomplete or broken JDK installation. I can't really help there. There are plenty suggestions on stackoverflow how to solve this issue.

**Comment by anydoby** [comment]
Thanks :) I'll continue trying.

2016-06-30 13:36 GMT+02:00 Sebastian Thomschke <notifications@github.com>:

> I am building it on an Ubuntu server via Jenkins, locally in Win10 64bit
> in the command line (currently Maven 3.3.9), as well as in a 32bit Eclipse
> installation (currently Mars SR2). I am not using any magic settings that I
> am aware of.
>
> You need to ensure that Maven itself is launched with a JDK it supports. I
> think Java7 is it's current minimum. When the toolchains.xml is configured
> properly Maven will fork processes for compilation and testing using the
> JDK defined in the toolchains.xml as jdk 1.5.
>
> "java/lang/NoClassDefFoundError: java/lang/Object" sounds like an
> incomplete or broken JDK installation. I can't really help there. There are
> plenty suggestions on stackoverflow how to solve this issue.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/sebthom/oval/pull/1#issuecomment-229633975>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AJhNh--Nssn-6wl1RicM7vrChLLmrHuvks5qQ6pYgaJpZM4I9r8j>
> .
>



-- 
Best regards,
Sergey Zolotaryov

**Pull request closed without merging**
